Vue.component(
    'factures-list',
    require('./FacturesList.vue').default
);
Vue.component(
    'facture-create',
    require('./FactureFormCreate.vue').default
);
Vue.component(
    'facture-details',
    require('./FactureDetails.vue').default
);
